python main.py --seed 1 --algorithm parseval
python main.py --seed 2 --algorithm parseval
python main.py --seed 3 --algorithm parseval
python main.py --seed 4 --algorithm parseval
python main.py --seed 5 --algorithm parseval
python main.py --seed 6 --algorithm parseval
python main.py --seed 7 --algorithm parseval
python main.py --seed 8 --algorithm parseval
python main.py --seed 9 --algorithm parseval
python main.py --seed 10 --algorithm parseval