CartPole-v1:
  0:
    gravity: 9.8
    masspole: 0.1
    force_mag: 10.0
  1:
    gravity: 19.6
    masspole: 0.1
    force_mag: 10.0
  2:
    gravity: 9.8
    masspole: 3.0
    force_mag: 7.0
  3:
    gravity: 9.8
    masspole: 3.0
    force_mag: 5.0

MountainCarContinuous-v0:
  0:   # Standard Right Goal
    power: 0.0015
    max_speed: 0.07
    goal_position: 0.45
    goal_velocity: 0.0

  1:   # HARD LEFT GOAL (balanced difficulty)
    power: 0.0008
    max_speed: 0.05
    goal_position: -100.05
    goal_velocity: 10000.0

  2:   # Weak Engine Right Goal
    power: 0.0007
    max_speed: 0.06
    goal_position: 0.45
    goal_velocity: 0.0

  3:   # Slippery Right Hill
    power: 0.0012
    max_speed: 0.15
    goal_position: 0.45
    goal_velocity: 10.0


Pendulum-v1: # g=gravity, m=mass, l=length of rod
  0:  
    g: 9.8
    max_torque: 2.0
    m: 1.0
    l: 1.0

  1:  
    g: 9.8
    max_torque: 2.0        # weaker but solvable
    m: 1.0
    l: 2.0

  2:  
    g: 9.8           # lower gravity → slower dynamics
    max_torque: 2.0
    m: 1.5
    l: 1.0

  3:  
    g: 9.8
    max_torque: 2.0
    m: 1.5
    l: 2.0