CartPole-v1:
  0:
    gravity: 9.8
    masspole: 0.1
    force_mag: 10.0
  1:
    gravity: 19.6
    masspole: 0.1
    force_mag: 10.0
  2:
    gravity: 9.8
    masspole: 3.0
    force_mag: 7.0
  3:
    gravity: 9.8
    masspole: 3.0
    force_mag: 5.0

Acrobot-v1:
  1:
    g: 11.0
    MAX_TORQUE: 1.0  
    LINK_MASS_1: 1.5
    LINK_MASS_2: 2.0
    LINK_MOI: 1.5 

  1:
    g: 25.0  
    MAX_TORQUE: 0.8 
    LINK_MASS_1: 1.0
    LINK_MASS_2: 1.5

  0:
    g: 7.0 
    MAX_TORQUE: 1.2
    LINK_LENGTH_1: 2.0
    LINK_LENGTH_2: 1.0
    
  3:
    g: 9.8
    MAX_TORQUE: 1.0
    LINK_MASS_1: 1.0
    LINK_MASS_2: 1.0
    LINK_LENGTH_1: 1.0
    LINK_LENGTH_2: 1.0